services:
  loki:
    image: grafana/loki:${LOKI_VERSION}
    container_name: loki
    networks:
      - monitoring
    ports:
      - 3100:3100
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3100/ready"]
      interval: 10s
      timeout: 5s
      retries: 3
    
  promtail:
    image: grafana/promtail:${PROMTAIL_VERSION}
    container_name: promtail
    networks:
      - monitoring
    volumes:
      - promtail_log:/var/log
      - promtail_etc:/etc/promtail
    depends_on:
      - loki
    command: -config.file=/etc/promtail/config.yml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080/ready"]
      interval: 10s
      timeout: 5s
      retries: 3

  grafana:
    image: grafana/grafana-oss:${GRAFANA_VERSION}
    container_name: grafana
    networks:
      - monitoring
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_USERS_ALLOW_SIGN_UP: ${GF_USERS_ALLOW_SIGN_UP}
    volumes:
      - grafana_volume:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - loki
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  monitoring:
    name: monitoring
    external: false

volumes:
  promtail_etc:
    driver: local
    name: promtail_etc
    driver_opts:
      type: none
      o: bind
      device: ./promtail_etc

  promtail_log:
    driver: local
    name: promtail_log
    driver_opts:
      type: none
      o: bind
      device: ./promtail_log

  grafana_volume:
    driver: local
    name: grafana_volume_loki