{
 "title": "ShoeHub Application",
 "tags": [
  "shoehub",
  "application"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Métricas da aplicação", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(system_runtime_cpu_usage[1m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(microsoft_aspnetcore_hosting_total_requests[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Métricas de venda", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "ShoeHub - Total de Vendas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "rate(shoehub_sales[1m])", "legendFormat": "{{ShoeType}}" }
   ]
  },
  {
   "title": "ShoeHub - Taxa de Vendas",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "shoehub_sales", "legendFormat": "{{ShoeType}}" }
   ]
  },
  {
   "title": "ShoeHub - Vendas por Marca",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    { "expr": "rate(shoehub_sales[5m])", "legendFormat": "{{ShoeType}}" }
   ]
  }
 ]
}