services:
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION}
    container_name: prometheus
    networks:
      - monitoring
    volumes:
      - prometheus_volume:/etc/prometheus
    ports:
      - "9090:9090"
    command: 
      - "--web.enable-remote-write-receiver" 
      - "--config.file=/etc/prometheus/prometheus.yml"

  node-exporter:
    image: prom/node-exporter:${NODE_EXPORTER_VERSION}
    container_name: node-exporter
    networks:
      - monitoring
    ports:
      - "9100:9100"

networks:
  monitoring:
    name: monitoring
    external: false

volumes:
  prometheus_volume:
    driver: local
    name: prometheus_volume_01_node
    driver_opts:
      type: none
      o: bind
      device: ./prometheus_volume_bind